on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Login to Docker hub"
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_TOKEN }}

      - name: "Building Docker image"
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/newImage .

      - name: "Push to Docker hub"
        run: docker push ${{ secrets.DOCKER_USERNAME }}/newImage 